### ISSUE TITLE
smallers downloads not getting captured properly.

### ISSUE THREAD

**Issue by karontenokami** [alexhua/Aria2-Explorer#211]
**Describe the bug**
i want to use an external downloader to get all my files.. but i don't get it why it won't just capture them automatically i have disabled the option that enables autocapture files at specific size. yet i'm still downloading small files thru google's dl manager.

**To Reproduce**
1. download small files
2. extension doesn't capture the download

**Expected behavior**
if i disable the option that only capture files at specific size ariaex should be capturing all the files.. not ignoring these specific files..

**Screenshots**

**Desktop (please complete the following information):**
 - windows 10 22h2
 -  - Chromium
 - 133.0.6869.0
**Additional context**

**Comment by alexhua** [comment]
To capture all downloading files regardless of their size, please set the file size option to `0` instead of disabling capture option.

Also: In some cases, the browser cannot obtain the file size, which may also lead to failure to capture. In this case, you could add the website domain to the website whitelist.

**Comment by karontenokami** [comment]
ok thanks
